## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
file_to_load = r"C:\Users\coope\Desktop\World_Weather_Analysis\Vacation_Search\WeatherPy_vacation.csv"

In [4]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv(file_to_load)
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Rikitea,PF,75.24,clear sky,-23.12,-134.97,Rikitea
1,7,Camalu,MX,82.99,scattered clouds,30.85,-116.07,Camalú
2,12,Salalah,OM,77.00,clear sky,17.02,54.09,Salalah
3,21,Alofi,NU,75.20,light rain,-19.06,-169.92,Alofi
4,23,Bengkulu,ID,75.67,overcast clouds,-3.80,102.27,Bengkulu
...,...,...,...,...,...,...,...,...
104,363,Itarema,BR,81.82,overcast clouds,-2.92,-39.92,Itarema
105,366,Abu Zabad,SD,83.98,clear sky,12.35,29.25,Abu Zabad
106,375,Mulki,IN,78.80,mist,13.10,74.80,Karnad
107,377,Grand-Santi,GF,89.67,broken clouds,4.25,-54.38,Grand-Santi
108,378,Kilindoni,TZ,79.23,light rain,-7.91,39.67,Kilindoni

In [5]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [6]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities.
mexico_vacation_df = vacation_df.loc[(vacation_df["Country"] == "MX")]
mexico_vacation_df.dropna()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,7,Camalu,MX,82.99,scattered clouds,30.85,-116.07,Camalú
50,173,Nuevo Progreso,MX,84.00,clear sky,23.17,-97.95,Sebastián Ríos
53,179,Pochutla,MX,89.01,scattered clouds,15.74,-96.47,Pochutla District
54,181,Ixtapa,MX,87.01,clear sky,20.70,-105.20,Puerto Vallarta
73,246,Tenosique,MX,75.20,overcast clouds,17.48,-91.43,Tenosique
83,278,Valle Hermoso,MX,81.00,few clouds,25.67,-97.83,Valle Hermoso
90,305,Guerrero Negro,MX,80.08,overcast clouds,27.98,-114.06,Guerrero Negro
101,351,Providencia,MX,89.01,overcast clouds,28.72,-111.58,Distrito de Riego de Hermosillo

In [8]:
new_column_order = ["City_ID", "City", "Country", "Lat","Lng", "Max Temp", "Current Description"]

In [10]:
mexico_vacation_df = mexico_vacation_df[new_column_order]

In [11]:
mexico_vacation_df

,City_ID,City,Country,Lat,Lng,Max Temp,Current Description
1,7,Camalu,MX,30.85,-116.07,82.99,scattered clouds
50,173,Nuevo Progreso,MX,23.17,-97.95,84.00,clear sky
53,179,Pochutla,MX,15.74,-96.47,89.01,scattered clouds
54,181,Ixtapa,MX,20.70,-105.20,87.01,clear sky
73,246,Tenosique,MX,17.48,-91.43,75.20,overcast clouds
83,278,Valle Hermoso,MX,25.67,-97.83,81.00,few clouds
90,305,Guerrero Negro,MX,27.98,-114.06,80.08,overcast clouds
101,351,Providencia,MX,28.72,-111.58,89.01,overcast clouds

In [12]:
start = float(input("What is your Starting City_ID from MX List you would like for your trip? "))
stop1 = float(input("What is your First Stop City_ID from MX List you would like for your trip? "))
stop2 = float(input("What is your Second Stop City_ID from MX List you would like for your trip? "))
stop3 = float(input("What is your Thirth Stop City_ID from MX List you would like for your trip? "))
end = float(input("What is your Last City_ID from MX List you would like for your trip? "))

In [13]:
 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] == stop1)]
vacation_start = vacation_start.iloc[0]

vacation_stop1 = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] == stop2)]
vacation_stop1 = vacation_stop1.iloc[0]

vacation_stop2 = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] == stop3)]
vacation_stop2 = vacation_stop2.iloc[0]

vacation_stop3 = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] == end)]
vacation_stop3 = vacation_stop3.iloc[0]

vacation_end = mexico_vacation_df.loc[(mexico_vacation_df["City_ID"] <= end)]
vacation_end = vacation_end.iloc[0] 
                                     
print("Your Starting Destination is " + vacation_start["City"] + ", " + vacation_start["Country"])
print("Your Frist Stop is " + vacation_stop1["City"] + ", " + vacation_stop1["Country"])
print("Your Second Stop is " + vacation_stop2["City"] + ", " + vacation_stop2["Country"])                                     
print("Your Thirth Stop is " + vacation_stop3["City"] + ", " + vacation_stop3["Country"])                                     
print("Your Last Stop in your vacation is " + vacation_end["City"] + ", " + vacation_end["Country"])

Your Starting Destination is Ixtapa, MX
Your Frist Stop is Tenosique, MX
Your Second Stop is Guerrero Negro, MX
Your Thirth Stop is Nuevo Progreso, MX
Your Last Stop in your vacation is Camalu, MX

In [14]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]]
print(start)

Lat     20.7
Lng   -105.2
Name: 54, dtype: object

In [15]:
stop1 = vacation_stop1[["Lat", "Lng"]]
print(stop1)

Lat    17.48
Lng   -91.43
Name: 73, dtype: object

In [16]:
stop2 = vacation_stop2[["Lat", "Lng"]]
print(stop2)

Lat     27.98
Lng   -114.06
Name: 90, dtype: object

In [17]:
stop3 = vacation_stop3[["Lat", "Lng"]]
print(stop3)

Lat    23.17
Lng   -97.95
Name: 50, dtype: object

In [18]:
end = vacation_end[["Lat", "Lng"]]
print(end)

Lat     30.85
Lng   -116.07
Name: 1, dtype: object

In [19]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING". I used "DRIVING"
import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)

start = (20.7, -105.2)
stop1 = (17.48, -91.43)
stop2 = (27.98, -114.06)
stop3 = (23.17, -97.95)
end = (30.85, -116.07)

fig = gmaps.figure()
sart2end_via_stops = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(sart2end_via_stops)
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
mexico_vacation_df = pd.concat([mexico_vacation_df],ignore_index=True)
mexico_vacation_df

,City_ID,City,Country,Lat,Lng,Max Temp,Current Description
0,7,Camalu,MX,30.85,-116.07,82.99,scattered clouds
1,173,Nuevo Progreso,MX,23.17,-97.95,84.00,clear sky
2,179,Pochutla,MX,15.74,-96.47,89.01,scattered clouds
3,181,Ixtapa,MX,20.70,-105.20,87.01,clear sky
4,246,Tenosique,MX,17.48,-91.43,75.20,overcast clouds
5,278,Valle Hermoso,MX,25.67,-97.83,81.00,few clouds
6,305,Guerrero Negro,MX,27.98,-114.06,80.08,overcast clouds
7,351,Providencia,MX,28.72,-111.58,89.01,overcast clouds

In [21]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in mexico_vacation_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = mexico_vacation_df[["Lat", "Lng"]]

In [25]:
# 11a. Add a marker layer for each city to the map.
city_mark = mexico_vacation_df["City"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))